############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]] 
name = "Gallery"
url = "gallery/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
name = "About"
url = "about/"
weight = 4

[[main]] 
name = "Contact"
url = "contact/"
weight = 5


# [[main]]
# weight = 5
# name = "Pages"
# hasChildren = true

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "blog/"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "contact/"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "authors/"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# footer menu
[[footer]] 
name = "Gallery"
url = "gallery/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4

