############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
<<<<<<< HEAD
url = "about/"
=======
url = "/about"
>>>>>>> upstream/main
weight = 2

[[main]]
name = "Elements"
<<<<<<< HEAD
url = "elements/"
=======
url = "/elements"
>>>>>>> upstream/main
weight = 3

[[main]]
weight = 4
name = "Pages"
<<<<<<< HEAD
hasChildren = true
=======
>>>>>>> upstream/main

[[main]]
parent = "Pages"
name = "Blog"
<<<<<<< HEAD
url = "blog/"
=======
url = "/blog"
>>>>>>> upstream/main

[[main]]
parent = "Pages"
name = "Contact"
<<<<<<< HEAD
url = "contact/"
=======
url = "/contact"
>>>>>>> upstream/main

[[main]]
parent = "Pages"
name = "Authors"
<<<<<<< HEAD
url = "authors/"
=======
url = "/authors"
>>>>>>> upstream/main

[[main]]
parent = "Pages"
name = "Categories"
<<<<<<< HEAD
url = "categories/"
=======
url = "/categories"
>>>>>>> upstream/main

[[main]]
parent = "Pages"
name = "404 Page"
<<<<<<< HEAD
url = "404/"
=======
url = "/404"
>>>>>>> upstream/main


# footer menu
[[footer]]
name = "About"
<<<<<<< HEAD
url = "about/"
=======
url = "/about"
>>>>>>> upstream/main
weight = 1

[[footer]]
name = "Elements"
<<<<<<< HEAD
url = "elements/"
=======
url = "/elements"
>>>>>>> upstream/main
weight = 2

[[footer]]
name = "Privacy Policy"
<<<<<<< HEAD
url = "privacy-policy/"
=======
url = "/privacy-policy"
>>>>>>> upstream/main
weight = 3
